---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azure-file-retain-dev
  namespace: dev
provisioner: file.csi.azure.com
parameters:
  skuName: Premium_ZRS
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
mountOptions:
 - dir_mode=0777
 - file_mode=0777
 - uid=0
 - gid=0
 - mfsymlinks
 - cache=strict
 - actimeo=30